# Generated by Django 5.2.9 on 2026-01-22 12:43

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_principal', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('video', models.FileField(blank=True, help_text='Fichier vidéo mp4', null=True, upload_to=core.models.upload_to_home)),
                ('video_poster', models.ImageField(blank=True, null=True, upload_to=core.models.upload_to_home)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to=core.models.upload_to_home)),
                ('featured_image_1', models.ImageField(blank=True, null=True, upload_to=core.models.upload_to_home)),
                ('featured_image_2', models.ImageField(blank=True, null=True, upload_to=core.models.upload_to_home)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Page d'accueil",
                'verbose_name_plural': "Pages d'accueil",
            },
        ),
        migrations.CreateModel(
            name='CarouselItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(upload_to=core.models.upload_to_home)),
                ('titre', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('homepage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carousel_items', to='core.homepage')),
            ],
            options={
                'verbose_name': 'Élément du carousel',
                'verbose_name_plural': 'Éléments du carousel',
                'ordering': ['ordre'],
            },
        ),
    ]
